### ISSUE TITLE
Using existing username to create new user 

### ISSUE THREAD

**Issue by Blyatman0692** [nurselaine/typeracer#15]
would cause client to freeze with Server: 0 status.

**Comment by nurselaine** [comment]
Hi - i can't recreate this issue. Can you please give instructions on how to reproduce this issue?

**Comment by Blyatman0692** [comment]
> Hi - i can't recreate this issue. Can you please give instructions on how to reproduce this issue?

I think there is a problem in my branch that is causing this, the problem does not exist in main brach.

**Comment by nurselaine** [comment]
closing this issue.
