### ISSUE TITLE
Not appending to database in server.java

### ISSUE THREAD

**Issue by michael-torkaman** [nurselaine/typeracer#8]
not appending to user_database.txt  properly. need to write to new line. on next run of server. server crashes. removing the empty lines at end of file fixes problem. Need to either correct how server reads from file. or correct how server writes to file. correcting both would be the best case. read correctly and write correctly.

**Comment by nurselaine** [comment]
This is what my user database file looks like when I create a new user profile. It appears to be making a new line each time it writes to the file. 

<img width="754" alt="Screenshot 2024-02-27 005949" src="https://github.com/nurselaine/typeracer/assets/96552092/166ee835-b99a-40b8-8f6c-b1aae9fcc3c8">

**Comment by michael-torkaman** [comment]
yeah im investigating it. currently. Thank you for the output. for me it was writing it to the same line and creating a a new line underneath it which i dont know how that is possible but will fix it in a moment!

**Comment by nurselaine** [comment]
that's very strange. I can look into it. maybe I added something into the last code I pushed up

**Comment by michael-torkaman** [comment]
Im pretty sure a big part of it is the changes i added to the file paths. because i tried to touch as little code that you wrote as possible. there is probably some logic somewhere that breaks when i changed the file path scheme. If the filepaths are changed to the windows ones the problem will go away.

**Comment by nurselaine** [comment]
I want to say my code has a good amount of bugs so wouldn't blame you for running into issues lol. Change whatever you think would be for the best.

**Comment by michael-torkaman** [comment]
simple fix. issue closed. needed to remove a "\n" from the end of the saveUserCredentials() in ClientHandler.java fixed it. added a line to throw an exception when loading the database in server.java just in case. but should be removed later on.
